FROM ubuntu
MAINTAINER QE
 
RUN apt-get clean
RUN apt-get -y update
RUN apt-get install -qq -y curl
RUN apt-get install -y unzip
RUN apt-get install -y git
RUN apt-get install -y wget
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Pacific
RUN apt-get install --reinstall -y software-properties-common
 

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
RUN export JAVA_HOME
# Define default command.
CMD ["bash"]


ENV MAVEN_VERSION 3.5.4

RUN mkdir -p /usr/share/maven \
  && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1 \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

VOLUME /root/.m2

CMD ["mvn"] 


RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  g++ \
  gcc \
  libc6-dev \
  libffi-dev \
  zlib1g-dev \
  libssl-dev \
  make
#install Google-chrome and Google driver
RUN apt-get -y update
RUN apt-get install -y unzip xvfb libxi6 libgconf-2-4 
RUN apt-get install -y gnupg2
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get -y update
RUN apt-get -y install google-chrome-stable
RUN google-chrome --version
RUN wget https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip
RUN mv -f chromedriver /usr/local/share/chromedriver
RUN ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
RUN ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
# Firefox browser to run the tests
#RUN apt-get install -y firefox
# Gecko Driver
#ENV GECKODRIVER_VERSION 0.29.1
#RUN wget --no-verbose -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
#RUN rm -rf /opt/geckodriver
#RUN tar -C /opt -zxf /tmp/geckodriver.tar.gz
#RUN rm /tmp/geckodriver.tar.gz
#RUN mv /opt/geckodriver /opt/geckodriver-$GECKODRIVER_VERSION
#RUN chmod 777 /opt/geckodriver-$GECKODRIVER_VERSION
#RUN ln -fs /opt/geckodriver-$GECKODRIVER_VERSION /usr/bin/geckodriver
#RUN ln -fs /opt/geckodriver-$GECKODRIVER_VERSION /usr/local/bin/geckodriver
#RUN ln -fs /opt/geckodriver-$GECKODRIVER_VERSION /usr/bin/wires
#RUN ln -fs /opt/geckodriver-$GECKODRIVER_VERSION /usr/local/bin/wires
ARG GIT_VERSION=1632314201574
RUN cd $HOME && GIT_VERSION=${GIT_VERSION} git config --global http.sslverify false
RUN cd $HOME && GIT_VERSION=${GIT_VERSION} git  clone -b master https://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@github.com/devrabbititsol/IdlyExpress.git
RUN cd $HOME/IdlyExpress&& GIT_VERSION=${GIT_VERSION}  mvn clean test -Ptestng.xml
